"""
Django settings for django_todo project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Importa el módulo os, que proporciona una forma de interactuar con el sistema operativo.
import os  

# Importa el paquete dj_database_url, que se utiliza para analizar URLs de bases de datos 
# y convertirlas en configuraciones que Django puede entender.
import dj_database_url  

# Comprueba si existe un archivo llamado 'env.py' en el directorio actual.
# os.path.isfile() devuelve True si el archivo especificado existe.
if os.path.isfile('env.py'):
    # Si 'env.py' existe, importa el módulo env para cargar las variables de entorno definidas en él.
    import env  




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ospa&^13ptj&dpifwl06)^@6wkt$u3#66f0@77+x@_o31n^6&n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'todo'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_todo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_todo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # La configuración por defecto, comentada, para usar una base de datos SQLite.
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',  # El backend de la base de datos que Django usará (SQLite en este caso).
    #     'NAME': BASE_DIR / 'db.sqlite3',  # La ubicación del archivo de la base de datos SQLite.
    # }
    
    # Configuración de la base de datos usando dj_database_url 
    # y una URL de base de datos almacenada en una variable de entorno.
    'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))  
    # dj_database_url.parse() convierte la URL de la base de datos en un 
    # diccionario de configuración que Django puede entender.
    # os.environ.get('DATABASE_URL') obtiene la URL de la base de datos desde las variables de entorno.
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
